---

- name: Ensure software-properties-common is installed
  package:
    name: software-properties-common
    state: present

- name: Add MariaDB APT key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present

- name: "Add MariaDB APT repo for version {{ mariadb_version }}"
  apt_repository:
    repo: "{{ mariadb_repo_url }}"
    update_cache: yes
    state: present
